AWSTemplateFormatVersion: '2010-09-09'
Description: ''
Resources:
  MyFunction:
    Properties:
      CodeUri: s3://bref-hello-world/17acd6e78eeeed839000739c4030bb6e
      Description: ''
      FunctionName: bref-hello-world
      Handler: index.php
      Layers:
      - arn:aws:lambda:us-east-1:209497400698:layer:php-73:4
      MemorySize: 1024
      Runtime: provided
      Timeout: 10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
